receivers:
  otlp:
    protocols:
      http:
        endpoint: :8080

connectors:
  spanmetrics:
    histogram:
      #! disable histogram to simplify data
      disable: true

processors:
  resource/deletes:
    attributes:
      - { key: host.arch, action: delete }
      - { key: host.name, action: delete }
      - { key: os.description, action: delete }
      - { key: process.command_args, action: delete }
      - { key: process.executable.path, action: delete }
      - { key: process.pid, action: delete }
      - { key: process.runtime.description, action: delete }
      - { key: process.runtime.name, action: delete }
      - { key: process.runtime.version, action: delete }
      - { key: telemetry.auto.version, action: delete }
      - { key: telemetry.sdk.language, action: delete }
      - { key: telemetry.sdk.name, action: delete }
      - { key: telemetry.sdk.version, action: delete }    
service:
  pipelines:
    metrics:
      receivers: [spanmetrics]
      processors: [resource/deletes]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [zipkin, spanmetrics]

exporters:
  zipkin:
    endpoint: "http://zipkin.apps.internal:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:18889"
    send_timestamps: true
    resource_to_telemetry_conversion:
      enabled: true
