scrape_configs:
- job_name: otel-col
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ['otel-col.apps.internal:18889']

- job_name: otel-agent
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
  - names:
    - q-s4.*.*.cf*.bosh.
    type: A
    port: 18889
